export const siteConfig = {
  name: "giftforlove",
  domain: "giftfor.love",
  shortTitle: "GiftFor.Love",
  title: "GiftFor.Love — Curated Gift Ideas for Every Occasion",
  description: "Find the perfect gift for everyone on your list. Thoughtful, curated gift ideas for every occasion, every person, and every budget.",
  tagline: "Find the Perfect Gift for Everyone",
  url: "https://giftfor.love",
  ogImage: "",
  colors: {
    primary: "#D4A853",
    primaryDark: "#2D1B0E",
    primaryLight: "#E8B4B8",
    secondary: "#9CAF88",
    accent: "#D4A853",
  },
  categories: [
    { key: "dad", label: "For Dad", description: "Thoughtful gift ideas for the father who deserves the best — from practical tools to heartfelt keepsakes." },
    { key: "mom", label: "For Mom", description: "Show your love with curated gifts for Mom — spa essentials, personalized treasures, and heartfelt surprises." },
    { key: "partner", label: "For Your Partner", description: "Romantic and meaningful gifts for your significant other — because love deserves to be celebrated." },
    { key: "kids", label: "For Kids", description: "Magical gifts that spark imagination and joy — toys, books, and experiences for children of all ages." },
    { key: "friends", label: "For Friends", description: "Celebrate your friendships with gifts that say 'you matter' — unique finds for your closest companions." },
    { key: "colleagues", label: "For Colleagues", description: "Professional yet personal gift ideas for coworkers — perfect for holidays, milestones, and thank-yous." },
    { key: "birthday", label: "Birthday", description: "Make birthdays unforgettable with carefully chosen gifts that match their personality and passions." },
    { key: "anniversary", label: "Anniversary", description: "Mark the milestone with timeless anniversary gifts — from first year celebrations to golden jubilees." },
    { key: "holiday", label: "Holiday", description: "Spread holiday cheer with curated gift guides for Christmas, Valentine's Day, Mother's Day, and more." },
    { key: "wedding", label: "Wedding", description: "Celebrate new beginnings with elegant wedding gifts — for the happy couple starting their journey together." },
  ] as { key: string; label: string; description: string }[],
};
